--CREATE DATABASE UNI;

USE UNI;

CREATE TABLE ROLE
(
	ID NVARCHAR(5) NOT NULL PRIMARY KEY,
	DESCRIPTION NVARCHAR(20) NOT NULL,

	USER_CREATE NVARCHAR(20) NOT NULL,
	DATE_CREATE DATETIME NOT NULL,
	USER_UPDATE NVARCHAR(20),
	DATE_UPDATE DATETIME,
)

CREATE TABLE USERS
(
	USERNAME NVARCHAR(20) NOT NULL PRIMARY KEY,
	PASSWORD NVARCHAR(20) NOT NULL,
	ROLE NVARCHAR(5),

	USER_CREATE NVARCHAR(20) NOT NULL,
	DATE_CREATE DATETIME NOT NULL,
	USER_UPDATE NVARCHAR(20),
	DATE_UPDATE DATETIME,

	FOREIGN KEY (ROLE) REFERENCES ROLE(ID),
)

CREATE TABLE FACULTY
(
	ID NVARCHAR(10) NOT NULL PRIMARY KEY,
	DESCRIPTION NVARCHAR(40) NOT NULL,

	USER_CREATE NVARCHAR(20) NOT NULL,
	DATE_CREATE DATETIME NOT NULL,
	USER_UPDATE NVARCHAR(20),
	DATE_UPDATE DATETIME,

)

CREATE TABLE CAMPUS
(
	ID NVARCHAR(10) NOT NULL PRIMARY KEY,
	DESCRIPTION NVARCHAR(40) NOT NULL,
	ADDRESS NVARCHAR(40) NOT NULL,

	USER_CREATE NVARCHAR(20) NOT NULL,
	DATE_CREATE DATETIME NOT NULL,
	USER_UPDATE NVARCHAR(20),
	DATE_UPDATE DATETIME,
)

CREATE TABLE CAREER
(
	ID VARCHAR(5) NOT NULL PRIMARY KEY,
	DESCRIPTION NVARCHAR(40) NOT NULL,
	FACULTY NVARCHAR(10),
	CAMPUS NVARCHAR(10),
	
	
	USER_CREATE NVARCHAR(20) NOT NULL,
	DATE_CREATE DATETIME NOT NULL,
	USER_UPDATE NVARCHAR(20),
	DATE_UPDATE DATETIME,

	
	FOREIGN KEY(FACULTY) REFERENCES FACULTY(ID),
	FOREIGN KEY(CAMPUS) REFERENCES CAMPUS(ID),
)

CREATE TABLE COURSE
(
	ID VARCHAR(6) PRIMARY KEY NOT NULL,
	DESCRIPTION NVARCHAR(40) NOT NULL,
	CREDITS INT NOT NULL, 
	FRECUENCY INT NOT NULL,
	HOURS INT NOT NULL,
	ID_CAREER VARCHAR(5) NOT NULL,

	FOREIGN KEY (ID_CAREER) REFERENCES CAREER(ID),
	USER_CREATE NVARCHAR(20) NOT NULL,
	DATE_CREATE DATETIME NOT NULL,
	USER_UPDATE NVARCHAR(20),
	DATE_UPDATE DATETIME,
)

CREATE TABLE STUDENT
(
	CARNET VARCHAR(10) PRIMARY KEY NOT NULL,
	NAME NVARCHAR(20) NOT NULL,
	LASTNAME NVARCHAR(20) NOT NULL,
	ADDRESS NVARCHAR(40),
	PHONE NVARCHAR(9),
	CAREER VARCHAR(5) NOT NULL,
	

	USER_CREATE NVARCHAR(20) NOT NULL,
	DATE_CREATE DATETIME NOT NULL,
	USER_UPDATE NVARCHAR(20),
	DATE_UPDATE DATETIME,

	FOREIGN KEY (CAREER) REFERENCES CAREER(ID),
)

CREATE TABLE STUDENT_COURSE
(
	ID_STUDENT VARCHAR(10) NOT NULL,
	ID_COURSE VARCHAR(6) NOT NULL,

	USER_CREATE NVARCHAR(20) NOT NULL,
	DATE_CREATE DATETIME NOT NULL,
	USER_UPDATE NVARCHAR(20),
	DATE_UPDATE DATETIME,

	FOREIGN KEY (ID_STUDENT) REFERENCES STUDENT(CARNET),
	FOREIGN KEY (ID_COURSE) REFERENCES COURSE(ID),
)